title: Stack Problems
description: My Personal Stack Problems
author: Lucas Farias
github: https://github.com/lffsantos
about: I am freelance developer. Currently doing more in backend, focused in Python and Django/Flask.
disqus_shortname: lucasfarias
google_analytics: UA-93337504-1
avatar_url: /static/img/lucas.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/lucas.farias.santos"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/lucasfariassantos/"
    - icon: fa-github
      link: "https://github.com/lffsantos"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lucasfarias.com.br" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 20
per_page: 20
paginate_path: "/page/:num/"


urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
